# Generated by Django 3.1.11 on 2021-07-21 16:18

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_auto_20210721_1918'),
        ('schools', '0006_auto_20210713_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='location_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='nearby_activities',
            field=models.ManyToManyField(blank=True, to='organizations.Activity'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
        migrations.AlterField(
            model_name='schoolmember',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_member', to='organizations.activity'),
        ),
    ]
