# Generated by Django 3.1.11 on 2021-07-21 16:33

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20210721_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location_lon',
        ),
        migrations.AddField(
            model_name='school',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='0,0', max_length=63),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
