# Generated by Django 3.1.11 on 2021-07-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_auto_20210721_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='distance_cache',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolmember',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_member', to='schools.school'),
        ),
    ]
