# Generated by Django 3.1.11 on 2021-07-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20210722_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='distance_cache',
            new_name='activity_distance_cache',
        ),
        migrations.RemoveField(
            model_name='school',
            name='nearby_activities',
        ),
    ]
