# Generated by Django 3.1.11 on 2021-07-21 16:33

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_auto_20210721_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='location_lon',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='location_lon',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='0,0', max_length=63),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='0,0', max_length=63),
        ),
    ]
